### PR TITLE
Solving #112

### LINKED ISSUE #112: The run view persists if not dismissed
The bug reported in: https://github.com/TheTorProject/ooniprobe-ios/issues/132 also happens on Android in `1.2.2-rc.1`

### PR DESCRIPTION
**Pull request by lorenzoPrimi**
Needs more testing, but I guess it's ok

Closes #112

### CODE REVIEW

**Comment by bassosimone** [comment]
The diff is very simple, but to properly sign-off this PR I also need to test on the emulator or on a device and I will not be able to do that until this afternoon.

**Comment by bassosimone** [comment]
I am now testing this

**Comment by bassosimone** [comment]
Okay, so, I have tested this and it works 👍. @lorenzoPrimi can you explain me why? (By just reading the diff I am not able to fully understand)

**Comment by bassosimone** [comment]
> By just reading the diff I am not able to fully understand)

Is it because the same activity - already open - can be activated by a new intent? So, having an handler for a new intent allows to deal with the screen drawing another test?

**Comment by lorenzoPrimi** [comment]
onNewIntent() is triggered only when the activity is already opened and you send it a new intent (so new parameters.

**Pull request merged**
