### PR TITLE
Edited the mobile app description

### PR DESCRIPTION
**Pull request by agrabeli**
@lorenzoPrimi @hellais I've updated/edited the app description (the same has been done for f-droid).

### CODE REVIEW

**Comment by lorenzoPrimi** [comment]
Should I modify the same file in the -iOS repo?

**Comment by hellais** [comment]
> Should I modify the same file in the -iOS repo?

I think we should probably have a single source of truth for these descriptions. I would suggest we consolidate all mobile app descriptions in one or the other repo and remove the duplication.

**Comment by lorenzoPrimi** [comment]
Yeah, and remove the description files from both repos

**Comment by hellais** [comment]
> Yeah, and remove the description files from both repos

humm, you probably want to keep it somewhere. Unless you have an idea of some other repo where the description should live.

**Comment by lorenzoPrimi** [comment]
The options we have are two:
1) Create a repo with descriptions and script to generate them
2) Keep them in bot repo (iOS - Android)

I guess 1 is the cleanest

**Comment by lorenzoPrimi** [comment]
@hellais  How do I name this new repo? where do I create it?
Or you want to create it and I'll commit files?

**Comment by hellais** [comment]
> @hellais How do I name this new repo? where do I create it?
> Or you want to create it and I'll commit files?

Let's just stick with keeping it in here (the android repo) and remove it from the iOS repo. This tool could maybe also be useful to make this task easier: https://docs.fastlane.tools/actions/supply/

**Comment by lorenzoPrimi** [comment]
Ok I will remove the files from the iOS repo and keep them here.
Can you modify the file scripts/gen-descriptions.py to accept ios or android param and generate the correspondent strings? @hellais

**Comment by hellais** [comment]
> Can you modify the file scripts/gen-descriptions.py to accept ios or android param and generate the correspondent strings?

Maybe the easy fix for this is just to create two `gen-descriptions.py` scripts called `gen-descriptions-ios.py` and `gen-descriptions-android.py`. Also did you look at fastlane? It seems like it would make this task much easier and automated.

**Comment by hellais** [comment]
@lorenzoPrimi I filed this ticket about that: https://github.com/TheTorProject/ooniprobe-android/issues/125

**Comment by lorenzoPrimi** [comment]
Yes seen it, but I don't find it useful for me now.

**Comment by hellais** [comment]
> Yes seen it, but I don't find it useful for me now.

Well it avoids you having to copy paste (and possibly making mistakes in doing so) all the descriptions and metadata for every possible language.

Is this not useful?

**Comment by lorenzoPrimi** [comment]
I said "for now" like there are other priorities, and the description is updated not often. 
In fact I will try it after the revamp that will need new screenshots and description.

**Comment by hellais** [comment]
> I said "for now" like there are other priorities, and the description is updated not often.

This PR you just merged actually updates the description, so you are going to have to update the description for all the languages once transifex translation converges.

**Comment by lorenzoPrimi** [comment]
Remember that on iOS to update the description we should upload a new build and there is no schedule release for now.

**Pull request merged**
